### ISSUE TITLE
Parecer sobre relatório da A1

### ISSUE THREAD

**Issue by fccoelho** [IgorMichels/MM4#1]
### Introdução
Boa descrição da evolução da situação epidemiológica no país e profunda revisão bibliográfica. Não precisa citar nominalmente o Professor  e nem a disciplina na introdução.  
A revisão dos artigos está muito boa, poderia ser integrada à introdução para aderir melhor ao formato de um artigo científico.

### Metodologia
Modelo bem definido e embasado nos acontecimentos reais referentes à COVID-19 na Itália. Vocês forma muito atenciosos à explicação do modelo mas ficaram alguns detalhes faltando, por exemplo: Justifica a forma funcional de beta(t) e definir melhor $t_k$.

### Bibliografia
Excelente.

**Comment by IgorMichels** [comment]
@fccoelho, uma pequena dúvida sobre a introdução... na explicação dos modelos na revisão de literatura a gente inseriu imagens para ilustrar os compartimentos. Eu posso manter essas imagens na introdução ou posso só referenciar a imagem e colocar no final do artigo? Caso referencie, acho que o ideal seria referenciar todas as imagens (apenas uma menção do tipo "conforme figura X"), colocando todas as imagens no final do artigo com os devidos label's.

**Comment by fccoelho** [comment]
Pode manter na Introdução!

**Comment by IgorMichels** [comment]
Certo, muito obrigado!
