### ISSUE TITLE
Sobre a estimação de parâmetros

### ISSUE THREAD

**Issue by IgorMichels** [IgorMichels/MM4#2]
Tentamos fazer a estimação de diversas formas, primeiro com o sherpa, mas não conseguimos instalar em nenhum dos nosso computadores e nem no JupyterHub. Em seguida tentamos realizar por interact para achar algumas possíveis prioris para a análise bayesiana, mas não funcionou de forma muito efetiva. No fim, optamos por realizar a otimização via mínimos quadrados, com peso 1 para o desvio quadrático da quantidade acumulada de óbitos e 1.5 da quantidade acumulada de infectados. Esses pesos foram os que deram o melhor fit para as curvas, então optamos por deixar assim os pesos.

**Comment by fccoelho** [comment]
Ok @IgorMichels, mas para referência:
![image](https://user-images.githubusercontent.com/140123/101340420-78d15c80-385e-11eb-8470-85a78d7180d4.png)
